on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Lint --- ${{ env.BRANCH_NAME }}'

  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Test'

  types:
    name: "Types"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Types'
