on: workflow_call

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: init-checks
        with:
          result-encoding: string
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              context: 'reusable-checks',
              state: 'pending',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: 'Reusable Workflow',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
  

  lint:
    needs: init
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Lint --- ${{ env.BRANCH_NAME }}'
      - run: sleep 1s

  test:
    needs: init
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Test'
      - run: sleep 3s

  types:
    needs: init
    name: "Types"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Types'
      - run: sleep 2s
      - run: exit 1

  end:
    needs: [lint, test, types]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    env:
      CHECKS_STATUS: ${{ needs.*.result == 'success' && 'success' || 'failure' }}
    steps:
      - run: |
          echo ${{ needs.lint.result }}
          echo ${{ needs.test.result }}
          echo ${{ needs.types.result }}
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              context: 'reusable-checks',
              state: '${{ env.CHECKS_STATUS }}',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: 'Reusable Workflow',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
      - if: ${{ env.CHECKS_STATUS != 'success' }}
        run: exit 1