on: workflow_call

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: init-checks
        with:
          result-encoding: string
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              context: 'reusable-checks',
              state: 'pending',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: 'Reusable Workflow',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
      - run: exit 1
  

  lint:
    needs: init
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Lint --- ${{ env.BRANCH_NAME }}'
      - run: sleep 1s

  test:
    needs: init
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Test'
      - run: sleep 3s

  types:
    needs: init
    name: "Types"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Types'
      - run: sleep 2s
      - run: exit 1

  end:
    needs: [ init, lint, test, types ]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/github-script@v7
        id: set-final-commit-status
        with:
          result-encoding: string
          script: |
            const hasFailed = ${{ contains(needs.*.result, 'failure') }} || ${{ contains(needs.*.result, 'skipped') }} || ${{ contains(needs.*.result, 'cancelled') }};
            const state = hasFailed ? 'failure' : 'success';
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              context: 'reusable-checks',
              state: state,
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: 'Reusable Workflow',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
            return state;
      - if: ${{ steps.set-final-commit-status.outputs.result == 'failure' }}
        run: exit 1